FilmStation.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmStation.Domain.Entities;
using FilmStation.WebUI.Models;
using FilmStation.Domain.Abstract;
using System.Text.RegularExpressions;

namespace FilmStation.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IFilmRepository repository;

        int PageSize = 20;

        public AdminController(IFilmRepository repo)
        {
            repository = repo;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        //Film
        //生成列表
        public ActionResult List(string name, string category, string language, string area, string year, int page = 1)
        {

            Category current = new Category();
            if ( !string.IsNullOrEmpty(category) )
            {
                current = repository.Categorys.Where(p => p.EnCateName == category).Distinct().FirstOrDefault();
            }
            ClassifyFilmViewModel viewmodel = new ClassifyFilmViewModel()
            {
                ClassifyInfo = new ClassifyInfo()
                {
                    Category = category,
                    Language = language,
                    Year = year,
                    Area = area,
                    Name = name,
                    Rate = null,
                },
                Films = repository.Films
                .Where(p => (string.IsNullOrEmpty(name) || p.Name.Contains(name)) && (string.IsNullOrEmpty(category)||p.Style.Contains(current.ChCateName)) && (string.IsNullOrEmpty(area) || p.Location.Contains(area)) && (string.IsNullOrEmpty(language) || p.Language.Contains(language)) && (string.IsNullOrEmpty(year) || p.PublishTime.Contains(year)) )
                .OrderBy(p => p.Id)
                .Skip((PageSize * (page - 1)))
                .Take(PageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Films.Where(p => (string.IsNullOrEmpty(name) || p.Name.Contains(name)) && (string.IsNullOrEmpty(category) || p.Style.Contains(current.ChCateName)) && (string.IsNullOrEmpty(area) || p.Location.Contains(area)) && (string.IsNullOrEmpty(language) || p.Language.Contains(language)) && (string.IsNullOrEmpty(year) || p.PublishTime.Contains(year))).Count()
                },
                CurrentCategory = category,

            };
            return View(viewmodel);
        }

        public ActionResult Create()
        {
            return View("Edit", new Film());
        }

        public ActionResult Edit(int filmId)
        {
            Film film = repository.Films.FirstOrDefault(p => p.Id == filmId);
            return View(film);
        }

        [HttpPost]
        public ActionResult Edit(Film film)
        {
            if(ModelState.IsValid)
            {
                repository.SaveFilm(film);
                return RedirectToAction("List");
            }
            else
            {
                return View(film);
            }
        }

        public ActionResult Delete(int filmId)
        {
            Film film = repository.Films.Where(p => p.Id == filmId).FirstOrDefault();
            if(film != null)
            {
                repository.DeleteFilm(film);
            }
            return RedirectToAction("List");
        }

        public ActionResult FilterForm()
        {
            ClassifyNav nav = new ClassifyNav()
            {
                Category = repository.Categorys.Distinct().AsEnumerable(),
                Language = repository.LanguageCollections.Select(x => x.Language).Distinct().AsEnumerable(),
                Area = repository.AreaCollections.Select( x => x.Area).Distinct().AsEnumerable(),
                Rate = repository.RateCollections.Select( x => x.Rate).Distinct().AsEnumerable(),
                Year = repository.YearCollections.Select( x => x.Year).Distinct().AsEnumerable(),
            };
            return PartialView(nav);
        }

        //List
        //Create
        //Edit
        //[httpPost]Edit
        //Delete
        
        //Category
        public ActionResult CateList()
        {
            IEnumerable<Category> CategoryList = repository.Categorys.Distinct().OrderBy(p => p.Id).AsEnumerable();
            return View(CategoryList);
        }
        public ActionResult CateCreate()
        {
            return View("CateEdit", new Category());
        }
        public ActionResult CateEdit(int id)
        {
            Category cate = repository.Categorys.Where(p => p.Id == id).FirstOrDefault();
            return View(cate);
        }
        [HttpPost]
        public ActionResult CateEdit(Category catecollection)
        {
            if (ModelState.IsValid)
            {
                repository.SaveCategory(catecollection);
                return RedirectToAction("CateList");
            }
            else
            {
                return View(catecollection);
            }
        }
        public ActionResult CateDelete(int id)
        {
            Category cate = repository.Categorys.Where(p => p.Id == id).FirstOrDefault();
            if (cate != null)
            {
                repository.DeleteCategory(cate);
            }
            return RedirectToAction("CateList");
        }

        //Year
        public ActionResult YearList()
        {
            IEnumerable<YearCollection> YearList = repository.YearCollections.Distinct().OrderBy(p => p.Id).AsEnumerable();
            return View(YearList);
        }
        public ActionResult YearCreate()
        {
            return View("YearEdit", new YearCollection());
        }
        public ActionResult YearEdit( int id)
        {
            YearCollection year = repository.YearCollections.Where(p => p.Id == id).FirstOrDefault();
            return View(year);
        }
        [HttpPost]
        public ActionResult YearEdit(YearCollection yearcollection)
        {
            if(ModelState.IsValid)
            {
                repository.SaveYear(yearcollection);
                return RedirectToAction("YearList");
            }
            else
            {
                return View(yearcollection);
            }
        }
        public ActionResult YearDelete(int id)
        {
            YearCollection year = repository.YearCollections.Where(p => p.Id == id).FirstOrDefault();
            if(year != null)
            {
                repository.DeleteYear(year);
            }
            return RedirectToAction("YearList");
        }

        //Rate
        public ActionResult RateList()
        {
            IEnumerable<RateCollection> RateList = repository.RateCollections.Distinct().OrderBy(p => p.Id).AsEnumerable();
            return View(RateList);
        }
        public ActionResult RateCreate()
        {
            return View("RateEdit", new RateCollection());
        }
        public ActionResult RateEdit(int id)
        {
            RateCollection rate = repository.RateCollections.Where(p => p.Id == id).FirstOrDefault();
            return View(rate);
        }
        [HttpPost]
        public ActionResult RateEdit(RateCollection ratecollection)
        {
            if(ModelState.IsValid)
            {
                repository.SaveRate(ratecollection);
                return RedirectToAction("RateList");
            }
            else
            {
                return View(ratecollection);
            }
        }
        public ActionResult RateDelete(int id)
        {
            RateCollection rate = repository.RateCollections.Where(p => p.Id == id).FirstOrDefault();
            if(rate != null)
            {
                repository.DeleteRate(rate);
            }
            return RedirectToAction("RateList");
        }

        //Area
        public ActionResult AreaList()
        {
            IEnumerable<AreaCollection> AreaList = repository.AreaCollections.Distinct().OrderBy(p => p.Id).AsEnumerable();
            return View(AreaList);
        }
        public ActionResult AreaCreate()
        {
            return View("AreaEdit", new AreaCollection());
        }
        public ActionResult AreaEdit(int id)
        {
            AreaCollection area = repository.AreaCollections.Where(p => p.Id == id).FirstOrDefault();
            return View(area);
        }
        [HttpPost]
        public ActionResult AreaEdit(AreaCollection areacollection)
        {
            if(ModelState.IsValid)
            {
                repository.SaveArea(areacollection);
                return RedirectToAction("AreaList");
            }
            else
            {
                return View(areacollection);
            }
        }
        public ActionResult AreaDelete(int id)
        {
            AreaCollection area = repository.AreaCollections.Where(p => p.Id == id).FirstOrDefault();
            if(area != null)
            {
                repository.DeleteArea(area);
            }
            return RedirectToAction("AreaList");
        }

        //Language
        public ActionResult LanguageList()
        {
            IEnumerable<LanguageCollection> LanguageList = repository.LanguageCollections.Distinct().OrderBy(p => p.Id).AsEnumerable();
            return View(LanguageList);
        }
        public ActionResult LanguageCreate()
        {
            return View("LanguageEdit", new LanguageCollection());
        }
        public ActionResult LanguageEdit(int id)
        {
            LanguageCollection language = repository.LanguageCollections.Where(p => p.Id == id).FirstOrDefault();
            return View(language);
        }
        [HttpPost]
        public ActionResult LanguageEdit(LanguageCollection language)
        {
            if(ModelState.IsValid)
            {
                repository.SaveLanguage(language);

FilmStation.WebUI/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmStation.Domain.Abstract;
using FilmStation.Domain.Entities;
using FilmStation.WebUI.Models;

namespace FilmStation.WebUI.Controllers
{
    public class FilmController : Controller
    {
        public int PageSize = 24;

        private IFilmRepository repository;

        public FilmController(IFilmRepository filmRepo)
        {
             repository = filmRepo;
        }

        public ActionResult List(string category, string year, string area, string language , int page = 1)
        {
            Category CurrentCategory = new Category();
            if(category != null)
            {
                CurrentCategory = repository.Categorys.Where(p => p.EnCateName == category).Distinct().FirstOrDefault();
            }
            FilmViewModel viewModel = new FilmViewModel
            {
                Films = repository.Films
                .Where(p => (category == null || p.Style.Contains(CurrentCategory.ChCateName)) && (string.IsNullOrEmpty(year) || p.PublishTime.Contains(year)) && (string.IsNullOrEmpty(area) || p.Location.Contains(area)) && (string.IsNullOrEmpty(language) || p.Language.Contains(language)) )
                .OrderBy(x => x.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = page,
                    TotalItems = repository.Films.Where(p => (string.IsNullOrEmpty(category) || p.Style.Contains(CurrentCategory.ChCateName)) && (string.IsNullOrEmpty(year) || p.PublishTime.Contains(year)) && (string.IsNullOrEmpty(area) || p.Location.Contains(area)) && (string.IsNullOrEmpty(language) || p.Language.Contains(language)) ).Count(),
                },
                ClassifyInfo = new ClassifyInfo
                {
                    Name = null,
                    Category = category,
                    Year = year,
                    Area = area,
                    Language = language,
                    Rate = null,
                },
                CurrentCategory = CurrentCategory.EnCateName
            };

            return View(viewModel);
        }

        //public ActionResult List(ClassifyInfo classInfo, int page = 1)
        //{
        //    ClassifyFilmViewModel viewModel = new ClassifyFilmViewModel
        //    {
        //        ClassifyInfo = classInfo,
        //        Films 
        //    }
        //}

        [HttpPost]
        public ActionResult Search(string keyvalue, int page = 1)
        {
            Session["SearchKey"] = keyvalue;
            SearchResultViewModel viewModel = new SearchResultViewModel
            {
                Films = repository.Films
                .Where(p => p.Name.Contains(keyvalue))
                .OrderBy(x => x.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    TotalItems = repository.Films.Where(p => p.Name.Contains(keyvalue)).Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = page,
                },
                KeyValue = keyvalue
            };
            return View(viewModel);
        }

        public ActionResult SearchResult(int page)
        {
            string keyvalue = (string)Session["SearchKey"];
            if(keyvalue == null)
            {
                return RedirectToAction("List");
            }
            SearchResultViewModel viewModel = new SearchResultViewModel
            {
                Films = repository.Films
                .Where(p => p.Name.Contains(keyvalue))
                .OrderBy(x => x.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    TotalItems = repository.Films.Where(p => p.Name.Contains(keyvalue)).Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = page,
                },
                KeyValue = keyvalue
            };

            return View("Search", viewModel);
        }

        public ActionResult Detail(int id)
        {
            Film film = repository.Films.Where(p => p.Id == id).FirstOrDefault();
            return View(film);
        }

        public ActionResult ClassifiedNav(ClassifyInfo classInfo)
        {
            ClassifiedNavViewModel viewmodel = new ClassifiedNavViewModel
            {
                ClassifyInfo = classInfo,
                Areas = repository.AreaCollections.Distinct().Where(p => p.IsShow == true).AsEnumerable(),
                Languages = repository.LanguageCollections.Distinct().Where(p => p.IsShow == true).AsEnumerable(),
                Years = repository.YearCollections.Distinct().Where(p => p.IsShow == true).AsEnumerable(),
            };
            return PartialView(viewmodel);
        }
    }
}

FilmStation.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmStation.Domain.Abstract;
using FilmStation.Domain.Entities;
using FilmStation.WebUI.Models;

namespace FilmStation.WebUI.Controllers
{
    public class NavController : Controller
    {

        private IFilmRepository repository;
        public NavController(IFilmRepository FilmRepo)
        {
            repository = FilmRepo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectCategory = category;
            IEnumerable<Category> Categories = repository.Categorys.Distinct().Where(p => p.IsShow == true).AsEnumerable();
            return PartialView(Categories);
        }
    }
}

FilmStation.WebUI/Views/Shared/FilmSummary.cshtml
@model FilmStation.Domain.Entities.Film

<div class="col-lg-2 col-md-3 col-sm-3 col-xs-6 filmsummary">
    <a href="@Url.Action("Detail", "Film", new { id = Model.Id})" >
        <div class="img-responsive imgsummary">
            <img class="img-responsive center-block" src="~/image/@Model.ImageName" />
        </div>
        <div class="imgdesc">
            <h5>@Model.Name.Split()[0]</h5>
        </div>
    </a>
</div>

FilmStation.WebUI/Views/Shared/SearchSummary.cshtml
@model FilmStation.Domain.Entities.Film

<a href="@Url.Action("Detail", "Film", new { id = Model.Id})" class="list-group-item clearfix">
    <div class="searchimgsummary">
        <img class="img-responsive" src="~/image/@Model.ImageName" />
    </div>
    <h4 style="font-weight: 700;">@Model.Name</h4>
    <p>@{if (Model.OtherName != "null")
        { @Model.OtherName}
    } </p>
    <p>语言：@Model.Language</p>
    <p>类型：@Model.Style</p>
</a>

FilmStation.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/jQuery/jquery-3.1.1.js" type="text/javascript"></script>
    <script src="~/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-fixed-top navbar-inverse navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        @Html.ActionLink("Films", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-example">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse" id="navbar-collapse-example">
                        <ul class="nav navbar-nav">
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <!-- body padding-top 随nav的高度改变 -->
        <script type="text/javascript">
            $(document).ready(function () {
                $("body").css("padding-top", $("nav").height() + 20 + "px");
            })
            $(window).resize(function () {
                $("body").css("padding-top", $("nav").height() + 20 + "px");
            });
        </script>

        @*<div class="row">
            <div class="col-lg-12">
                <form action="@Url.RouteUrl("search1", new { controller = "Film", action = "Search"})" name="Search" method="post" class="form-inline" role="form">
                    <div class="input-group col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
                        <input name="keyvalue" type="text" class="form-control" placeholder="输入要搜索的电影名字" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">搜索</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>*@
        <hr />
        @RenderBody()
        <hr />
        <script src="~/Scripts/customed/HidPager.js" type="text/javascript"></script>
        <footer style="text-align:center">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Film Station</p>
        </footer>
    </div>
</body>
</html>

FilmStation.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/jQuery/jquery-3.1.1.js" type="text/javascript"></script>
    <script src="~/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-fixed-top navbar-inverse navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        @Html.ActionLink("Films", "List", "Film", new { area = "" }, new { @class = "navbar-brand" })
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-example">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse" id="navbar-collapse-example">
                        <ul class="nav navbar-nav">
                            @{ Html.RenderAction("Menu", "Nav");}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>    
        <!-- body padding-top 随nav的高度改变 -->
        <script type="text/javascript">
            $(document).ready(function () {
                $("body").css("padding-top", $("nav").height() + 20 + "px");
            })
            $(window).resize(function () {
                $("body").css("padding-top", $("nav").height() + 20 + "px");
            });
        </script>

        <div class="row">
            <div class="col-lg-12">
                <form action="@Url.RouteUrl("search1", new { controller = "Film", action = "Search"})" name="Search" method="post" class="form-inline" role="form">
                    <div class="input-group col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
                        <input name="keyvalue" type="text" class="form-control" placeholder="输入要搜索的电影名字" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">搜索</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
        <hr />
        @RenderBody()
        <hr />
        <script src="~/Scripts/customed/HidPager.js" type="text/javascript"></script>
        <footer style="text-align:center">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Film Station</p>
        </footer>
    </div>
</body>
</html>